"""OmniQuant LWC/LET calibration for the fake-QDQ path."""

from .runtime import (
    DEFAULT_OMNIQUANT_EPOCHS,
    DEFAULT_OMNIQUANT_INIT_LWC_LOGIT,
    DEFAULT_OMNIQUANT_LET_LR,
    DEFAULT_OMNIQUANT_LWC_LR,
    DEFAULT_OMNIQUANT_MAX_GRAD_NORM,
    DEFAULT_OMNIQUANT_WEIGHT_DECAY,
    OMNIQUANT_CALIBRATION_COMPUTE_DTYPE,
    OMNIQUANT_CALIBRATION_FORWARD_MODE,
    OMNIQUANT_LOSS_COMPUTE_DTYPE,
    OMNIQUANT_QUANTIZATION_COMPUTE_DTYPE,
    OmniQuantConfig,
    OmniQuantSummary,
    apply_omniquant_layers,
    restore_omniquant_layers_from_checkpoints,
)

__all__ = (
    "DEFAULT_OMNIQUANT_EPOCHS",
    "DEFAULT_OMNIQUANT_INIT_LWC_LOGIT",
    "DEFAULT_OMNIQUANT_LET_LR",
    "DEFAULT_OMNIQUANT_LWC_LR",
    "DEFAULT_OMNIQUANT_MAX_GRAD_NORM",
    "DEFAULT_OMNIQUANT_WEIGHT_DECAY",
    "OMNIQUANT_CALIBRATION_COMPUTE_DTYPE",
    "OMNIQUANT_CALIBRATION_FORWARD_MODE",
    "OMNIQUANT_LOSS_COMPUTE_DTYPE",
    "OMNIQUANT_QUANTIZATION_COMPUTE_DTYPE",
    "OmniQuantConfig",
    "OmniQuantSummary",
    "apply_omniquant_layers",
    "restore_omniquant_layers_from_checkpoints",
)
